name: Semantic Release

on:
  push:
    branches: [ main, chore/#6-semantic-versioning ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install Dependencies
        run: yarn install
      - name: Build Application
        run: yarn build
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn run release
